# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: rjdrk25
# "service" is the name of this project. This will also be added to your AWS resource names.
service: Serverless-AWS

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x

plugins:
  - serverless-offline
  - serverless-prune-plugin
  - serverless-plugin-include-dependencies

custom:
  prune:
    automatic: true
    number: 1

package:
  exclude:
    - node_modules/** 
  
functions:
  servicioGET:
    handler: handlers/handlerGET.servicioGET
    package:
      patterns:
        - "handlers/handlerGET.js"
    events: 
      - httpApi:
          path: /servicioGET
          method: get

  servicioPOST:
    handler: handlers/handlerPOST.servicioPOST
    package:
      patterns:
        - "handlers/handlerPOST.js"
    events:
      - httpApi:
          path: /servicioPOST
          method: post
  servicioMoment:
    handler: handlers/handlerMoment.GetMoment
    package:
      patterns:
        - "handlers/handlerMoment.js"
    events:
      - httpApi:
          path: /servicioMoment
          method: get
